export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const NEXT_STEP = "NEXT_STEP";
export type NEXT_STEP = typeof NEXT_STEP;

export const PREVIOUS_STEP = "PREVIOUS_STEP";
export type PREVIOUS_STEP = typeof PREVIOUS_STEP;
